language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.8.5
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.4.22

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py install

# command to run tests
script:
  - python setup.py test
  - python manage.py test codespeed
