language: python
python:
  - 2.7
  - 3.5
branches:
  only:
    - master
env:
  global:
    - DJANGO_SETTINGS_MODULE=sample_project.settings
  matrix:
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.1
install:
  - pip install flake8
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py install
before_script:
   flake8 codespeed
script:
  - python manage.py test codespeed
